_wandb:
    value:
        cli_version: 0.24.2
        e:
            x7cbwxvnoq9jqd9ho6j06gm3sqtilqtw:
                codePath: bp_3_assortative.py
                codePathLocal: bp_3_assortative.py
                cpu_count: 40
                cpu_count_logical: 40
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "53660876800"
                        used: "9949392896"
                email: busatomattea@gmail.com
                executable: /home/busato/venvs/assortative_partitions/bin/python
                git:
                    commit: e9feb573bd0be4ec328655308e99f6e3433ccfba
                    remote: https://github.com/matteabusato/assortative_partitions.git
                gpu: Tesla V100-PCIE-32GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-PCIE-32GB
                      uuid: GPU-621d4230-d01a-7684-86d6-de73fc6012dc
                host: i01
                memory:
                    total: "201910202368"
                os: Linux-5.14.0-70.30.1.el9_0.x86_64-x86_64-with-glibc2.34
                program: /home/busato/assortative_partitions/bp_3_assortative.py
                python: CPython 3.9.10
                root: /home/busato/assortative_partitions
                slurm:
                    cluster_name: izar
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x00000000FF
                    cpu_bind_list: "0x00000000FF"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "8"
                    cpus_per_task: "8"
                    distribution: cyclic
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: master
                    job_cpus_per_node: "8"
                    job_end_time: "1772703250"
                    job_gid: "30204"
                    job_gpus: "0"
                    job_id: "2802104"
                    job_name: bp_test_run
                    job_nodelist: i01
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: normal
                    job_start_time: "1772616850"
                    job_uid: "309744"
                    job_user: busato
                    jobid: "2802104"
                    launch_node_ipaddr: 10.91.27.1
                    localid: "0"
                    mem_per_node: "8192"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: i01
                    nprocs: "1"
                    ntasks: "1"
                    procid: "0"
                    script_context: prolog_task
                    srun_comm_host: 10.91.27.1
                    srun_comm_port: "45879"
                    step_gpus: "0"
                    step_id: "0"
                    step_launcher_port: "45879"
                    step_nodelist: i01
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /home/busato/assortative_partitions
                    submit_host: izar1
                    task_pid: "940911"
                    tasks_per_node: "1"
                    topology_addr: t1.ibsw3.i01
                    topology_addr_pattern: switch.switch.node
                    tres_per_task: cpu:8
                    umask: "0022"
                startedAt: "2026-03-04T09:34:14.588361Z"
                writerId: x7cbwxvnoq9jqd9ho6j06gm3sqtilqtw
        m: []
        python_version: 3.9.10
        t:
            "3":
                - 2
                - 3
                - 13
                - 16
                - 61
                - 62
            "4": 3.9.10
            "5": 0.24.2
            "12": 0.24.2
            "13": linux-x86_64
D:
    value: 20
H:
    value: 6
LOG_EVERY:
    value: 1000
M_target:
    value:
        - "0.33333333333333333333333333333333333333333333333333333333333333333333333333333333"
        - "0.33333333333333333333333333333333333333333333333333333333333333333333333333333333"
        - "0.33333333333333333333333333333333333333333333333333333333333333333333333333333333"
MAX_ITER:
    value: 10000000
"N":
    value: 1002
THRESHOLD:
    value: "1E-21"
chi_init:
    value:
        - - "0.5"
          - "0E+2"
          - "0E+2"
        - - "0E+2"
          - "0.25"
          - "0E+2"
        - - "0E+2"
          - "0E+2"
          - "0.25"
damping:
    value: "0.01"
initialization_chi:
    value: personalized
loss_mu:
    value: soft_l1
mu0:
    value:
        - "0"
        - "0"
        - "0"
seed:
    value: 537898
settingmu:
    value: previous
